type Server = {
  server_id: number;
  host: string;
  port: number;
  name: string;
  vanity: string;
  owner_id: number;
  monthly_votes: number;
  description: string;
  long_description: string;
  website_url: string;
  discord_url: string;
  trailer_url: string;
  tags: string[];
  is_bedrock: boolean;
  whitelisted: boolean;
  approved: boolean;
  premium: boolean;
  scraped: boolean;
  archived: boolean;
  last_updated: Date;
  created_at: Date;
  offline_since: Date;
  online: boolean;
  favicon: string;
  players_online: number;
  player_data: object[];
  pinged_at: Date;
};

export type { Server };
