name: autodeploy
on:
  push:
    branches:
      - v2
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: build & deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: bash -c "cd v2.minecraft.global && ./update.sh"
